### ISSUE TITLE
ros2 Connection to websocket server closed

### ISSUE THREAD

**Issue by zmoth** [ravijo/vue-ros-demo#1]
Thank you very much for your project.
I used Raspberry PI 4b, ubuntu22.04, ros2-humble
I successfully enabled the following three lines of commands
```bash
ros2 launch rosbridge_server rosbridge_websocket_launch.xml
ros2 run demo_nodes_py add_two_ints_server
ros2 run demo_nodes_py talker
```

Then I modify the contents in vue
```vue
   callService () {
      // First, we create a Service client with details of the service's name and service type.
      this.servieClient = new ROSLIB.Service({
        ros: this.ros,
        name: '/add_two_ints',
        serviceType: 'example_interfaces/srv/AddTwoInts'
      })
```

```vue
const allowedMessageType = 'std_msgs/msg/String'
```

In my rosbridge_server, the generated log is as follows
```
 ros2 launch rosbridge_server rosbridge_websocket_launch.xml
[INFO] [launch]: All log files can be found below /home/moth/.ros/log/2023-04-20-13-42-16-624199-raspi-moth-28858
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rosbridge_websocket-1]: process started with pid [28869]
[INFO] [rosapi_node-2]: process started with pid [28871]
[rosbridge_websocket-1] [INFO] [1681969339.873179216] [rosbridge_websocket]: Rosbridge WebSocket server started on port 9090
[rosbridge_websocket-1] WARNING:tornado.access:400 GET / (172.168.54.80) 3.85ms
[rosbridge_websocket-1] WARNING:tornado.access:404 GET /favicon.ico (172.168.54.80) 5.08ms
[rosbridge_websocket-1] WARNING:tornado.access:400 GET / (172.168.53.67) 12.27ms
[rosbridge_websocket-1] WARNING:tornado.access:404 GET /favicon.ico (172.168.53.67) 1.63ms
[rosbridge_websocket-1] WARNING:tornado.access:400 GET / (172.168.53.67) 13.11ms
[rosbridge_websocket-1] [INFO] [1681972144.758611581] [rosbridge_websocket]: Client connected. 1 clients total.
[rosbridge_websocket-1] [INFO] [1681972538.483212324] [rosbridge_websocket]: Client disconnected. 0 clients total.
[rosbridge_websocket-1] [INFO] [1681972540.274459186] [rosbridge_websocket]: Client connected. 1 clients total.
[rosbridge_websocket-1] [INFO] [1681972605.619892256] [rosbridge_websocket]: Client disconnected. 0 clients total.
[rosbridge_websocket-1] [INFO] [1681972606.434376677] [rosbridge_websocket]: Client connected. 1 clients total.

```
The webpage is as follows:
![image](https://user-images.githubusercontent.com/55644167/233296560-30e7e70a-d360-4981-ac28-b71e5eb57a0f.png)

I'm new to both ros and vue, so I hope it's not a stupid issue :)

**Comment by zmoth** [comment]
It worked when I changed the ip address to the Raspberry PI ip
I used Windows to ssh Raspberry PI in the same LAN
```vue
app.config.globalProperties.ros = new ROSLIB.Ros({
  url: 'ws://localhost:9090/'
})
```
```vue
app.config.globalProperties.ros = new ROSLIB.Ros({
  url: 'ws://172.168.54.80:9090/'
})
```

**Comment by zmoth** [comment]
I tested the following 4 ip, Only two are connected on the remote host.
- [ ] localhost:9090
- [ ] 127.0.0.1:9090
- [x] raspi-moth.local:9090
- [x] 172.168.54.80:9090

**Comment by ravijo** [comment]
@zmoth 


Thanks for reporting.

In case of having multiple PC (more specifically, `rosbridge_server` running on a remote machine), you must use the correct IP address. The localhost and 127.0.0.1 refer to the same device. So your node can not connect to `rosbridge_server`
 

> It worked when I changed the ip address to the Raspberry PI ip

I am glad you made it work!


By the way, I did not test it with ROS 2. However, I am glad that it works perfectly. If you have time, can you please share the code base? OR simply create a pull request. I would like to add the steps you reported to the [README.md](https://github.com/ravijo/vue-ros-demo/blob/9e6d34a43119023fcf0fb825ca1e37a3000c98b7/README.md) file:

```console
$ ros2 launch rosbridge_server rosbridge_websocket_launch.xml
$ ros2 run demo_nodes_py add_two_ints_server
$ ros2 run demo_nodes_py talker
```

**Comment by zmoth** [comment]
Ok, I'm going to create a pull request. Thank you
