### ISSUE TITLE
ask for backend code (C++) corresponding to the Github project

### ISSUE THREAD

**Issue by wangfafu** [ravijo/vue-ros-demo#3]
Now I have successfully implemented the topic communication for my ROS. However, we encountered a problem with service communication (both the backend and front-end did not report any errors), maybe there's a problem in (serviceType: `rospy_tutorials/AddTwoInts`), and I should have made an error in the backend project. So, can you share the backend code (C++) corresponding to the Github project?
Thank you very much!

**Comment by ravijo** [comment]
@Flipped101 

> can you share the backend code (C++) corresponding to the Github project?

I am sorry, but no additional code is required to run [vue-ros-demo](https://github.com/ravijo/vue-ros-demo#demonstration). This is why I used existing ROS messages and services. Below are the [prerequisites](https://github.com/ravijo/vue-ros-demo#prerequisite) needed for running it:


```
$ roslaunch rosbridge_server rosbridge_websocket.launch
$ rostopic pub /listener std_msgs/String "Hello, World"
$ rosrun rospy_tutorials add_two_ints_server
```

Please make sure you have [dependencies](https://github.com/ravijo/vue-ros-demo#dependencies) installed.

**Comment by wangfafu** [comment]
thank you very much!!!




王法福
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ravijo/vue-ros-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ravijo/vue-ros-demo] ask for backend code (C++) corresponding to the Github project (Issue #3)





 
@Flipped101
  
can you share the backend code (C++) corresponding to the Github project?
  
I am sorry but there is no addtional code required to run vue-ros-demo.  This is why I used existing ROS messages and services.  Below are the prerequisite needed for running it:
 $ roslaunch rosbridge_server rosbridge_websocket.launch $ rostopic pub /listener std_msgs/String "Hello, World" $ rosrun rospy_tutorials add_two_ints_server  
Please make sure you have dependencies installed.

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
